### ISSUE TITLE
Relevant work

### ISSUE THREAD

**Issue by Hritikbansal** [dqxiu/ICL_PaperList#2]
Hi @dqxiu ,

Great curation of papers!

Perhaps, you can add our recent work on ICL to the ReadMe and survey under Model Analysis category.

Here is the arxiv link and Twitter sunmary:

https://arxiv.org/abs/2212.09095

https://twitter.com/hbXNov/status/1605219662819909632?s=20&t=bXbKb-JUG9xvdlLsdzOBbw

**Comment by dqxiu** [comment]
Thanks! That's a very interesting and insightful paper, I've added it to our paper list. And we will add it to the survey in the next version.

**Comment by Hritikbansal** [comment]
Hi, thanks!

I would suggest that a better tag would be 'rethinking' or 'analysis' instead of 'corpus' for our work.

**Comment by dqxiu** [comment]
Sorry, that's a mistake and I've updated the tag :).
