### ISSUE TITLE
Could I add a paper on ICL?

### ISSUE THREAD

**Issue by SongtaoLiu0823** [dqxiu/ICL_PaperList#7]
Hi,

Could I add one paper which uses ICL for retrosynthetic planning (scientific problem)?

FusionRetro: Molecule Representation Fusion via In-Context Learning for Retrosynthetic Planning, 23 ICML
code: https://github.com/SongtaoLiu0823/FusionRetro
arXiv: https://arxiv.org/pdf/2209.15315.pdf

I will update the arXiv with our ICML camera ready version.

Thanks!

**Comment by dqxiu** [comment]
Sure! Added.
